export type {
  ObservationIssue,
  ObservedCallable,
  ObservedCallableValueFacet,
  ObservedDeclaration,
  ObservedDeclarationFacets,
  ObservedDeclarationKind,
  ObservedExport,
  ObservedMember,
  ObservedObjectValueFacet,
  ObservedParameter,
  ObservedSurface,
  ObservedType,
  ObservedTypeFacet,
  ObservedTypeParameter,
  SourceLocation,
  SourcePosition,
} from './model.ts'
